service: demo-bun-hono
image: gambala/demo-bun-hono
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
labels:
  traefik.http.routers.demo-bun-hono-web.rule: Host(`hono.gambala.pro`)
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
healthcheck:
  interval: 10s
  path: /
builder:
  multiarch: false
